git:
 image: f99aq8ove/gitbucket
 restart: always
 volumes:
     - ./data:/gitbucket
 ports:
     - 20080:8080
     - 29418:29418
 command: java -jar /opt/gitbucket.war --port=8080 --prefix=/gitbucket
